name: Generate and Cache OpenWrt dl Directory

on:
  workflow_dispatch:

jobs:
  generate-dl:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib gperf \
          libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone upstream lede repo
      run: git clone --depth=1 https://github.com/coolsnowwolf/lede.git

    - name: Copy your .config into lede/.config
      run: |
        cp configs/JDcloud_AX1800PRO.config lede/.config

    - name: Update and install feeds
      working-directory: ./lede
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate .config and download sources
      working-directory: ./lede
      run: |
        make defconfig
        make download -j$(nproc)

    - name: Upload dl/ directory back to your repo
      run: |
        mkdir -p sync-dir
        rsync -a lede/dl/ sync-dir/dl/
        cd sync-dir
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git init
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git checkout -b dl-cache
        git add dl/
        git commit -m "Add pre-downloaded dl directory"
        git push -f origin dl-cache
