name: OpenWrt Build with Precached dl

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
          ssh:
            description: "Enable SSH debugging"
            required: false
            default: "true"

jobs:
  download-dl:
    name: Download DL directory
    runs-on: ubuntu-22.04
    outputs:
      cache-hit: ${{ steps.dl-cache.outputs.cache-hit }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Cache dl directory
      id: dl-cache
      uses: actions/cache@v4
      with:
        path: dl
        key: ${{ runner.os }}-lede-dl-${{ hashFiles('feeds.conf.default') }}
        restore-keys: |
          ${{ runner.os }}-lede-dl-

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib gperf \
          libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Prepare feeds
      run: |
        git clone https://github.com/coolsnowwolf/lede
        cd lede

        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate .config
      run: |
        [ -e $CONFIG_FILE ] && mv configs/JDcloud_AX1800PRO.config .config
    
    - name: Setup tmate session (SSH debug)
      if: ${{ github.event.inputs.ssh == 'true' || contains(github.event.head_commit.message, '[ssh]') }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false  # 仅允许触发者访问 SSH 会话

    - name: Download source (dl)
      if: steps.dl-cache.outputs.cache-hit != 'true'
      run: |
        make download -j8
